apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pcv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-admin-data-pcv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi