apiVersion: v1
kind:  Secret
metadata: 
  name: postgres-db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

  PGADMIN_DEFAULT_EMAIL: YWRtaW5Ab3pvbmV0ZWNoLmNvbQ==
  PGADMIN_DEFAULT_PASSWORD: YWRtaW5AcGFzcw==