version: '3'
services:
  nats:
    image: nats
    container_name: nats
    ports:
      - '4222:4222'
      - '8222:8222'
    command:
      [
        '--http_port',
        '8222',
        '--cluster_name',
        'NATS',
        '--cluster',
        'nats://0.0.0.0:6222',
      ]
