import { ThemeProvider } from '@web/components/contexts/theme-provider';
import AppSidebar from '@web/components/global/app-sidebar';
import AppBar from '@web/components/global/app-topbar';
import { TooltipProvider } from '@web/components/ui/tooltip';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import cn from '../utils/cn';
import './globals.css';
import TransitionProvider from '@web/components/contexts/transition-provider';
import { Toaster } from '@web/components/ui/toast';
import getMe from '@web/data/user/getMe';
import { getAccounts } from '@web/data/auth/authentications';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getMe();
  const accounts = await getAccounts();
  const communities = [
    {
      slug: 'astu-muslim-jama',
      name: 'Astu Muslim Jama',
      image: '',
    },
    {
      slug: 'dodola-muslim-jama',
      name: 'Dodola Muslim Jama',
      image: '',
    },
    {
      slug: 'adama-muslim-jama',
      name: 'Adama Muslim Jama',
      image: '',
    },

    {
      slug: 'astu-muslim-jama2',
      name: 'Astu Muslim Jama',
      image: '',
    },
    {
      slug: 'dodola-muslim-jama2',
      name: 'Dodola Muslim Jama',
      image: '',
    },
    {
      slug: 'adama-muslim-jama2',
      name: 'Adama Muslim Jama',
      image: '',
    },

    {
      slug: 'astu-muslim-jama3',
      name: 'Astu Muslim Jama',
      image: '',
    },
    {
      slug: 'dodola-muslim-jama3',
      name: 'Dodola Muslim Jama',
      image: '',
    },
    {
      slug: 'adama-muslim-jama3',
      name: 'Adama Muslim Jama',
      image: '',
    },

    {
      slug: 'astu-muslim-jama4',
      name: 'Astu Muslim Jama',
      image: '',
    },
    {
      slug: 'dodola-muslim-jama4',
      name: 'Dodola Muslim Jama',
      image: '',
    },
    {
      slug: 'adama-muslim-jama4',
      name: 'Adama Muslim Jama',
      image: '',
    },

    {
      slug: 'astu-muslim-jama5',
      name: 'Astu Muslim Jama',
      image: '',
    },
    {
      slug: 'dodola-muslim-jama5',
      name: 'Dodola Muslim Jama',
      image: '',
    },
    {
      slug: 'adama-muslim-jama5',
      name: 'Adama Muslim Jama',
      image: '',
    },

    {
      slug: 'astu-muslim-jama6',
      name: 'Astu Muslim Jama',
      image: '',
    },
    {
      slug: 'dodola-muslim-jama6',
      name: 'Dodola Muslim Jama',
      image: '',
    },
    {
      slug: 'adama-muslim-jama6',
      name: 'Adama Muslim Jama',
      image: '',
    },

    {
      slug: 'astu-muslim-jama7',
      name: 'Astu Muslim Jama',
      image: '',
    },
    {
      slug: 'dodola-muslim-jama7',
      name: 'Dodola Muslim Jama',
      image: '',
    },
    {
      slug: 'adama-muslim-jama7',
      name: 'Adama Muslim Jama',
      image: '',
    },
  ];
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen w-full bg-background text-foreground font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TransitionProvider>
            <TooltipProvider>
              <div className="flex w-full">
                <AppSidebar
                  user={user}
                  accounts={accounts ?? []}
                  communities={communities}
                />
                <div className="flex flex-col w-full">
                  <AppBar user={user} />
                  {children}
                </div>
              </div>
            </TooltipProvider>
          </TransitionProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
