version: '3.8'

services:
  mongo-db:
    image: mongo:7.0.2-jammy
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ozonetech
      - MONGO_INITDB_ROOT_PASSWORD=ozone_pass
    volumes:
      - mongo-data-volume:/var/lib/mongo/data

  mongo-express:
    image: mongo-express:1.0-20-alpine3.18
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ozonetech
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ozone_pass
      - ME_CONFIG_BASICAUTH_USERNAME=ozonetech
      - ME_CONFIG_BASICAUTH_PASSWORD=ozone_pass
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      
    volumes:
      - mongo-express-data-volume:/var/lib/mongo-data-volume

volumes:
  mongo-data-volume:
  mongo-express-data-volume: