apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo
        image: "mongo:7.0.2-jammy"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data-volume
          mountPath: /var/lib/mongo/data
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret
                key: MONGO_ROOT_USERNAME

          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret
                key: MONGO_ROOT_PASSWORD
                
        
      - name: mongo-express
        image: "mongo-express:1.0.0-20-alpine3.18"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret
                key: MONGO_ROOT_USERNAME
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret
                key: MONGO_ROOT_PASSWORD
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-db-configmap
                key: ME_CONFIG_MONGODB_SERVER


        volumeMounts:
        - name: mongo-express-data-volume
          mountPath: /var/lib/mongo-data-volume
          
      volumes:
      - name: mongo-data-volume
        persistentVolumeClaim:
          claimName: mongo-data-pcv
      - name: mongo-express-data-volume
        persistentVolumeClaim:
          claimName: mongo-express-data-pcv
       
       