apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
spec:
  selector:
    app: mongo-db
  ports:
  - name: mongo-db
    protocol: TCP
    port: 27017
    targetPort: 27017
  - name: mongo-express
    protocol: TCP
    port: 8081
    targetPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express-external-service
spec:
  selector:
    app: mongo-db
  type: LoadBalancer
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30002
  - name: mongo-express
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30021